### ISSUE TITLE
What is difference between AutoDisposeChangeNotifierProvider vs ChangeNotifierProvider

### ISSUE THREAD

**Issue by dyardy** [anfeichtinger/flutter_production_boilerplate_riverpod#1]
I was not familiar with AutoDisposeChangeNotifierProvider and am finding it bit challenging to find the difference.  Both seem to work

```
// final AutoDisposeChangeNotifierProvider<ThemeModeState> themeProvider =
//     ChangeNotifierProvider.autoDispose(
//         (AutoDisposeChangeNotifierProviderRef<ThemeModeState> ref) {
//   return ThemeModeState();
// });

final themeProvider = ChangeNotifierProvider<ThemeModeState>((ref){
  return ThemeModeState();
});

```

**Comment by reafeichtinger** [comment]
Their usage is pretty much the same. From the documentation I got, that the AutoDisposeChangeNotifierProvider will destroy their state when no-longer listened to, while the ChangeNotifierProvider will keep it's last state. For that Provider.autoDispose is used. More info can be found in the [Riverpod Documentation](https://riverpod.dev/docs/concepts/modifiers/auto_dispose/ )
