### ISSUE TITLE
Move from color swatches to color schemes

### ISSUE THREAD

**Issue by harrybawsac** [anfeichtinger/flutter_production_boilerplate_riverpod#2]
[Color scheme will be the preferred way to configure colors as all of the other color things will be phased out.](https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/theme_data.dart#L290)

More info: https://github.com/flutter/flutter/issues/91772

**Comment by reafeichtinger** [comment]
Thanks for the heads up. I've implemented the necessary changes in order to switch to ColorSchemes. I'll leave the issue open for a few days. If there is something wrong or missing feel free to use this issue to tell me.

**Comment by harrybawsac** [comment]
Cool, will check it out this weekend!

**Comment by harrybawsac** [comment]
Great stuff!
