### ISSUE TITLE
Move from 2018 to 2021 typography naming

### ISSUE THREAD

**Issue by harrybawsac** [anfeichtinger/flutter_production_boilerplate_riverpod#3]
The text theme won't have names like `headline2` but rather `displayMedium`.

More info: https://github.com/flutter/flutter/blob/master/packages/flutter/lib/src/material/text_theme.dart#L86

**Comment by reafeichtinger** [comment]
Also thanks, for this. Maybe you can also find the time to check it like Issue #2.

**Comment by harrybawsac** [comment]
Looks good!
